;*********************************************
;	memory.asm
;		- Memory layout
;*********************************************

;BIOS_BOOT_START EQU 0xFE000
;BIOS_BOOT_END EQU 0xFFFFF
;this is 1kb
;16_BIT_INTERRUPTION_TABLE_START EQU 0x00000
;16_BIT_INTERRUPTION_TABLE_END EQU 0x003FF

;256b
;BIOS_DATA_START EQU 0x00400
;BIOS_DATA_END EQU 0x004FF

;BIOS_INTERRUPT_SERVICE_ROUTINES_START EQU 0x0E05B
;BIOS_INTERRUPT_SERVICE_ROUTINES_END EQU  0x0FFFE

;*********************************************
;	Boot Loader
;*********************************************

SETUP_SECTORS EQU  0x4
BOOT_LOADER_ADDRESS EQU 0x07c00
BOOT_LOADER_SIZE EQU 0x00020
BOOT_LOADER_SAFE_ADDRESS EQU 0x90000
SETUP_ADDRESS EQU BOOT_LOADER_ADDRESS + BOOT_LOADER_SIZE
;SYSSEG  = 0x1000
;ENDSEG = SYSSEG + SYSSIZE

STACK_SIZE EQU 0xFF00



